version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: otus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: otus-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management Plugin
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
